name: Test & Deploy Storybook to GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  storybook-build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: /////////////// Checkout code ///////////////
        uses: actions/checkout@v4

      - name: /////////////// Installing dependencies ///////////////
        run: npm i --force

      - name: /////////////// Install Playwright ///////////////
        run: npx playwright install --with-deps

      - name: /////////////// Build Storybook ///////////////
        run: npm run build-storybook

      - name: /////////////// Serve Storybook and run tests ///////////////
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npm run storybook --silent" \
            "npx wait-on tcp:6006 && npm run test-storybook"