name: Storybook Interaction Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  storybook-build-and-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: /////////////// Checkout code ///////////////
        uses: actions/checkout@v4

      - name: /////////////// Use Node.js ${{ matrix.node-version }} ///////////////
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: /////////////// Installing dependencies ///////////////
        run: npm ci --force

      - name: /////////////// Install Playwright ///////////////
        run: npx playwright install --with-deps

      - name: /////////////// Build Storybook ///////////////
        run: npm run build-storybook --quiet

      - name: /////////////// Serve Storybook and run tests ///////////////
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006" \
            "npx wait-on tcp:127.0.0.1:6006 && npm run test-storybook"